- hosts: my_vm
  become: yes
  tasks:
    - name: Pull MySQL Docker image
      community.docker.docker_image:
        name: mysql
        tag: latest
        source: pull

    - name: Run MySQL container for Hammad
      community.docker.docker_container:
        name: mysql-server-hammad
        image: mysql:latest
        state: started
        env:
          MYSQL_ROOT_PASSWORD: "hammad_root_password"
          MYSQL_DATABASE: "hammad_zabbix"
          MYSQL_USER: "hammad_zabbix"
          MYSQL_PASSWORD: "hammad_zabbix"
        ports:
          - "3312:3306"

    - name: Pull Zabbix Docker image
      community.docker.docker_image:
        name: zabbix/zabbix-server-mysql
        tag: latest
        source: pull

    - name: Run Zabbix container for Hammad
      community.docker.docker_container:
        name: zabbix-hammad
        image: zabbix/zabbix-server-mysql:latest
        state: started
        ports:
          - "8090:80"
          - "10058:10051"
        env:
          DB_SERVER_HOST: "mysql-server-hammad"
          MYSQL_USER: "hammad_zabbix"
          MYSQL_PASSWORD: "hammad_zabbix"
          MYSQL_DATABASE: "hammad_zabbix"

    - name: Pull Nagios Docker image
      community.docker.docker_image:
        name: jasonrivers/nagios
        tag: latest
        source: pull

    - name: Run Nagios container for Hammad
      community.docker.docker_container:
        name: nagios-hammad
        image: jasonrivers/nagios:latest
        state: started
        ports:
          - "8091:80"

    - name: Pull Prometheus Docker image
      community.docker.docker_image:
        name: prom/prometheus
        tag: v2.30.3
        source: pull

    - name: Run Prometheus container for Hammad
      community.docker.docker_container:
        name: prometheus-hammad
        image: prom/prometheus:v2.30.3
        state: started
        ports:
          - "8092:9090"
